### ISSUE TITLE
裝了之後 ch a.cpp 沒有東西

### ISSUE THREAD

**Issue by fro11o** [MROS/contest_helper#1]
我用 Windows Ubuntu 18-04 clone 好之後，
用指令 ch a.cpp 之後，
有產生 a.cpp 這個檔案，
但是裡面是空的沒有預先載入 include 那些，
請問是哪裡做錯了嗎，感謝！

**Comment by MROS** [comment]
已修正路徑問題，請您再試一次看看

**Comment by fro11o** [comment]
可以成功載入了，感謝！
